### ISSUE TITLE
When will t4cam-ctrl support RQX-59G?

### ISSUE THREAD

**Issue by QQting** [tier4/tier4_automotive_hdr_camera#21]
Hello my friends,

Our customers are waiting for **t4cam-ctrl** to tune camera parameters.
Can I know when will t4cam-ctrl be ready for RQX-59G?

I just gave a simple test for t4cam-ctrl, here are what I found:
- t4cam_sdk-1.4.2-rqx.deb failed to be installed on RQX-59G
- t4cam_sdk-1.4.2-Linux.deb can be installed on RQX-59G
- To use t4cam-ctrl on RQX-59G, the i2c address of C1 camera driver has to be <0x1b> and <0x1c>, but currently we are using <0x1d> and <0x1e> to avoid built-in audio codec i2c <0x1c> confliction on RQX-59G
- In t4cam-ctrl-gui, the port index mapping is wrong

**Comment by bookbridge** [comment]
Hi @QQting,

As you correctly pointed out, currently t4cam-ctrl will not work with RQX-59G as we need to modify i2c address.
We will fix it within this month. I'll let you know once it is available.

**Comment by bookbridge** [comment]
Hi @QQting, I've modified t4cam-ctrl for RQX-59G.

It works on my side but could you try this? (this deb package is for RQX-59G only). I'll also put this on the release page if this is OK.

[t4cam_sdk-rqx59g.zip](https://github.com/tier4/tier4_automotive_hdr_camera/files/14716569/t4cam_sdk-rqx59g.zip)

**Comment by QQting** [comment]
Hi @bookbridge 

Thanks for your quick fix. Now t4cam-ctrl works well! Thank you!
