### ISSUE TITLE
Open multiple C1 camera issue

### ISSUE THREAD

**Issue by QQting** [tier4/tier4_automotive_hdr_camera#6]
Hi there,

I'm using RQX-58G (JetPack 4.6) with four ISX021-C1 cameras connected as below screenshot.
![image](https://user-images.githubusercontent.com/320113/213077473-1f592b71-1a11-4fd3-b287-9f02a34d3945.png)

When I use these cameras with gst-launch-1.0, all things are going well.
But when I use gscam on ROS Melodic env to open cameras, I have encountered many times that some of the four cameras doesn't publish any data, and there are no error messages. When I faced this issue, I have to close the abnormal port and re-open again until it successfully start publishing data.

Is it an issue from gscam? Are there any solution to fix this?
Thank you.

**Comment by yk-fujii** [comment]
Hi @QQting
Thanks for your report.

This issue is related to the issue #1.

Current drivers require cameras connected to the same deserializer to start streaming at the same time.
Described in "2.5. Visualize camera output using gstreamer" in the manual

We are planning to fix it in the next driver version, which will be released in February.

**Comment by QQting** [comment]
> Current drivers require to start streaming at the same time when cameras connected to the same deserializer. Described in "2.5. Visualize camera output using gstreamer" in the manual

Hi @yk-fujii 
I think my cameras (cam1, cam3, cam5, cam7) are connected to different deserializers.

**Comment by yk-fujii** [comment]
@QQting 
Sorry, I misunderstood.
Is there anything logged in dmesg?

**Comment by QQting** [comment]
There are slight differences between normal and abnormal dmesg logs, I'm not sure if this helps.

normal:
![image](https://user-images.githubusercontent.com/320113/216272558-b4dd7f2d-0df2-4e67-9ae2-278df0fee6c1.png)

abnormal:
![image](https://user-images.githubusercontent.com/320113/216272891-c99e519b-69af-4f05-8216-8158a36b4a1e.png)
