### ISSUE TITLE
Add DTS Property to select an arbitrary MAX9296 GPI/MFP for Fsync

### ISSUE THREAD

**Issue by cti-lewasko** [tier4/tier4_automotive_hdr_camera#8]
Hi,

Could a DTS property be added to the tier4-max9296 driver to select an arbitrary MFP/GPI on the deserializer for the fsync signal? Adding this feature would allow for greater portability between platforms.

Thank you,

**Comment by yk-fujii** [comment]
@cti-lewasko sorry for late response.

Could you provide more information on how you would like to modify tier4-max9296.c?
If you could give me a patch, I would like to add properties to DTS so that we can switch.

**Comment by yk-fujii** [comment]
MFP settings have been added since v1.3.0.
It can be specified by kernel parameter ( `fsync_mfp` ).


https://github.com/tier4/tier4_automotive_hdr_camera/blob/main/drivers/src/tier4-isx021.c#L303
