### ISSUE TITLE
3D CAD models of the camera

### ISSUE THREAD

**Issue by MikhailBertrand** [tier4/tier4_automotive_hdr_camera#9]
Hi, I've purchased one of your cameras the other day.
This isn't a question about the driver for the camera but I was wondering if there are any plans on releasing official 3D CAD models (e.g. step file) of your cameras. I only need the model of the outer case of the camera and it would be very helpful if there is one when integrating the camera into other projects (plus, showing it on rviz).
Thank you for your attention to this matter.

**Comment by yk-fujii** [comment]
@MikhailBertrand 
Hi, Sorry for the late reply.
Do you still have requests for 3d models?
We are planning to add it when the TIER IV website is renewed.

**Comment by yk-fujii** [comment]
@MikhailBertrand 
Hi, we have updated our web page and now the cad files are available for download.
Please check the item "Do you have exterior CAD data?"
https://sensor.tier4.jp/faq-and-contact
